/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe — returns 200 when all dependencies are up, 503 otherwise.
         *
         *     Reads the explicit state flags set by the lifespan manager. Safe to call
         *     at any point without touching connection pool objects directly.
         */
        get: operations["readiness_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kalshi/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kalshi Health
         * @description Probe authenticated Kalshi REST connectivity via GET /portfolio/balance.
         *
         *     Returns sanitized connectivity metadata only — no account financial data.
         */
        get: operations["kalshi_health_api_kalshi_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kalshi/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kalshi Get Markets
         * @description Retrieve markets from Kalshi for discovery and bootstrap.
         *
         *     Calls the public GET /markets Kalshi endpoint. Auth headers are sent when
         *     credentials are configured (avoids unauthenticated rate-limit buckets) but
         *     are not required — the upstream endpoint is publicly accessible.
         *
         *     This is a REST discovery/bootstrap endpoint only. Live market state will
         *     be delivered via WebSocket in a future slice.
         */
        get: operations["kalshi_get_markets_api_kalshi_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kalshi/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kalshi Get Events
         * @description Retrieve events from Kalshi for discovery and bootstrap.
         *
         *     Events are the primary grouping abstraction for related markets.  Each
         *     event contains one or more markets representing different outcomes of the
         *     same real-world occurrence.  The category field enables domain-level
         *     navigation across crypto, politics, sports, and other Kalshi categories.
         *
         *     When with_nested_markets=True, each event includes all its markets in a
         *     single response — this is the recommended path for powering the workstation
         *     "related markets" panel from a bootstrap call.
         *
         *     Calls the public GET /events Kalshi endpoint. Auth headers are sent when
         *     credentials are configured (avoids unauthenticated rate-limit buckets).
         *
         *     This is a REST discovery/bootstrap endpoint only. Live market state will
         *     be delivered via WebSocket in a future slice.
         */
        get: operations["kalshi_get_events_api_kalshi_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kalshi/events/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kalshi Get Event
         * @description Retrieve a single Kalshi event by ticker, including all nested markets.
         *
         *     Always requests with_nested_markets=true so that the event object contains
         *     its full market list in a single round-trip.  This is the direct lookup
         *     path for powering the workstation "related markets" panel when a user
         *     opens a specific market — identify the event_ticker from the market, then
         *     call this endpoint to get all sibling markets.
         *
         *     Returns 404 (not_found) when Kalshi responds with HTTP 404.
         *     Returns 502 (upstream_failure) for other upstream errors.
         */
        get: operations["kalshi_get_event_api_kalshi_events__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kalshi/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kalshi Get Series
         * @description Retrieve series from Kalshi for category-level navigation.
         *
         *     Series are templates for recurring events and carry the category and tags
         *     that power the workstation domain navigation pane.  Use the category param
         *     to narrow to a specific domain; leave it empty to get all series.
         *
         *     Note: the Kalshi GET /series endpoint has no pagination cursor — all
         *     matching series are returned in a single response per the documented API.
         *
         *     Calls the public GET /series Kalshi endpoint.  Auth headers are sent when
         *     credentials are configured (avoids unauthenticated rate-limit buckets).
         */
        get: operations["kalshi_get_series_api_kalshi_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kalshi/markets/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kalshi Get Market
         * @description Retrieve a single Kalshi market by ticker with full price and rules context.
         *
         *     Returns the enriched MarketDetailDTO, which adds settlement state, price
         *     movement, strike definition, and rules fields on top of the browse-level
         *     MarketDTO fields.  This is the lookup path for populating a market
         *     inspection pane or providing order entry context.
         *
         *     Returns 404 (not_found) when Kalshi responds HTTP 404.
         *     Returns 502 (upstream_failure) for other upstream errors.
         */
        get: operations["kalshi_get_market_api_kalshi_markets__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories
         * @description Return all distinct Kalshi categories with their series count.
         *
         *     Computed in-process from the cached series list — no extra Kalshi call.
         *     Categories are sorted alphabetically.  Use the category name as a filter
         *     for GET /api/catalog/series.
         *
         *     Example response:
         *       { "categories": [
         *           { "name": "Crypto",    "series_count": 12 },
         *           { "name": "Politics",  "series_count": 47 },
         *           { "name": "Sports",    "series_count": 31 }
         *         ] }
         */
        get: operations["get_categories_api_catalog_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series
         * @description Return the series list from cache, optionally filtered by category.
         *
         *     The full series list is cached in Redis for 15 minutes.  Filtering and
         *     sorting happen in-process on the cached data — no extra Kalshi call.
         *
         *     Use the series ticker from results as the series_ticker query param on
         *     GET /api/catalog/events to list all events for that series.
         */
        get: operations["get_series_api_catalog_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Events
         * @description Return a paginated list of Kalshi events, fetched live.
         *
         *     Markets are NOT included in list results — use GET /api/catalog/events/{ticker}
         *     to retrieve a single event with its full market list.
         *
         *     Typical navigation:
         *       1. GET /api/catalog/series?category=Sports             → pick a series_ticker
         *       2. GET /api/catalog/events?series_ticker=KXNBA&status=open  → pick an event
         *       3. GET /api/catalog/events/KXNBA-...                   → see all markets
         */
        get: operations["get_events_api_catalog_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/events/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event Detail
         * @description Return a single Kalshi event with its full nested markets list.
         *
         *     Use this to populate a market selection pane after the user picks an event
         *     from the events list.  All markets for the event are included inline.
         *
         *     Returns 404 when the event does not exist on Kalshi.
         *     Returns 502 on upstream errors.
         */
        get: operations["get_event_detail_api_catalog_events__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/markets/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Detail
         * @description Return full detail for a single Kalshi market.
         *
         *     Includes price movement fields, strike definition, and settlement rules
         *     on top of the standard market browse fields.  Use this to populate an
         *     order entry panel or market inspection pane.
         *
         *     Returns 404 when the market does not exist on Kalshi.
         *     Returns 502 on upstream errors.
         */
        get: operations["get_market_detail_api_catalog_markets__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Markets
         * @description Placeholder endpoint — returns scaffold status and connection health.
         */
        get: operations["list_markets_api_markets__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CatalogEventDetailResponse */
        CatalogEventDetailResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "not_found" | "upstream_failure";
            event?: components["schemas"]["EventDTO"] | null;
        };
        /** CatalogEventsResponse */
        CatalogEventsResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "upstream_failure";
            /** Events */
            events: components["schemas"]["EventDTO"][];
            /** Cursor */
            cursor?: string | null;
        };
        /** CatalogMarketDetailResponse */
        CatalogMarketDetailResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "not_found" | "upstream_failure";
            market?: components["schemas"]["MarketDetailDTO"] | null;
        };
        /** CatalogSeriesResponse */
        CatalogSeriesResponse: {
            /** Series */
            series: components["schemas"]["SeriesDTO"][];
            /** Total */
            total: number;
            /** Cache Ttl Seconds */
            cache_ttl_seconds?: number | null;
        };
        /** CategoriesResponse */
        CategoriesResponse: {
            /** Categories */
            categories: components["schemas"]["CategorySummary"][];
        };
        /** CategorySummary */
        CategorySummary: {
            /** Name */
            name: string;
            /** Series Count */
            series_count: number;
        };
        /** ConnectionStatus */
        ConnectionStatus: {
            /** Postgres */
            postgres: boolean;
            /** Redis */
            redis: boolean;
        };
        /** DependencyChecks */
        DependencyChecks: {
            /** Postgres */
            postgres: boolean;
            /** Redis */
            redis: boolean;
        };
        /**
         * EventDTO
         * @description Minimal internal event representation for discovery and bootstrap use.
         *
         *     Events are the natural grouping container for related markets on Kalshi.
         *     A market belongs to exactly one event (via event_ticker), and all markets
         *     in the same event represent different outcomes of the same real-world
         *     occurrence.  The category field on EventDTO is the primary signal for
         *     domain-level navigation (crypto, politics, sports, etc.).
         *
         *     When with_nested_markets=True is requested, the markets list is populated
         *     with the same MarketDTO shape used by the /kalshi/markets endpoint.
         */
        EventDTO: {
            /** Event Ticker */
            event_ticker: string;
            /** Series Ticker */
            series_ticker?: string | null;
            /** Title */
            title?: string | null;
            /** Sub Title */
            sub_title?: string | null;
            /** Category */
            category?: string | null;
            /** Mutually Exclusive */
            mutually_exclusive?: boolean | null;
            /**
             * Markets
             * @default []
             */
            markets: components["schemas"]["MarketDTO"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** KalshiEventDetailResponse */
        KalshiEventDetailResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "not_found" | "upstream_failure";
            /** Message */
            message: string;
            event?: components["schemas"]["EventDTO"] | null;
        };
        /** KalshiEventsResponse */
        KalshiEventsResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "upstream_failure";
            /** Message */
            message: string;
            /** Events */
            events: components["schemas"]["EventDTO"][];
            /** Cursor */
            cursor?: string | null;
        };
        /** KalshiHealthResponse */
        KalshiHealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "missing_config" | "auth_failure" | "upstream_failure";
            /** Message */
            message: string;
            /** Provider */
            provider: string;
            /** Authenticated */
            authenticated: boolean;
            /** Probe */
            probe: string;
            /** Base Url */
            base_url: string;
            /** Environment */
            environment: string;
        };
        /** KalshiMarketDetailResponse */
        KalshiMarketDetailResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "not_found" | "upstream_failure";
            /** Message */
            message: string;
            market?: components["schemas"]["MarketDetailDTO"] | null;
        };
        /** KalshiMarketsResponse */
        KalshiMarketsResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "upstream_failure";
            /** Message */
            message: string;
            /** Markets */
            markets: components["schemas"]["MarketDTO"][];
            /** Cursor */
            cursor?: string | null;
        };
        /** KalshiSeriesResponse */
        KalshiSeriesResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "upstream_failure";
            /** Message */
            message: string;
            /** Series */
            series: components["schemas"]["SeriesDTO"][];
        };
        /**
         * MarketDTO
         * @description Browse-focused internal market representation.
         *
         *     Covers the fields most useful for evaluating a market quickly in a list,
         *     ladder, or related-markets panel.  Sourced from GET /markets and from
         *     the nested markets returned by GET /events when with_nested_markets=true.
         *
         *     Fields are confirmed against docs.kalshi.com/api-reference/market/get-market.
         *     Fields noted as deprecated in the Kalshi docs are kept while the upstream
         *     API still returns them, but new display code should prefer yes_sub_title
         *     and no_sub_title over the deprecated title/subtitle fields.
         */
        MarketDTO: {
            /** Ticker */
            ticker: string;
            /** Event Ticker */
            event_ticker?: string | null;
            /** Market Type */
            market_type?: string | null;
            /** Yes Sub Title */
            yes_sub_title?: string | null;
            /** No Sub Title */
            no_sub_title?: string | null;
            /** Title */
            title?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Status */
            status?: string | null;
            /** Open Time */
            open_time?: string | null;
            /** Close Time */
            close_time?: string | null;
            /** Yes Bid Dollars */
            yes_bid_dollars?: string | null;
            /** Yes Ask Dollars */
            yes_ask_dollars?: string | null;
            /** Last Price Dollars */
            last_price_dollars?: string | null;
            /** Volume Fp */
            volume_fp?: string | null;
            /** Volume 24H Fp */
            volume_24h_fp?: string | null;
            /** Open Interest Fp */
            open_interest_fp?: string | null;
        };
        /**
         * MarketDetailDTO
         * @description Extended single-market detail DTO for GET /markets/{ticker}.
         *
         *     Inherits all browse fields from MarketDTO and adds settlement state,
         *     price-movement context, strike definition, and market rules — the fields
         *     needed to render a full market inspection pane or inform order entry.
         *
         *     Fields confirmed from docs.kalshi.com/api-reference/market/get-market.
         *     The ``liquidity_dollars`` field is explicitly omitted: the Kalshi docs
         *     state it is deprecated and will always return "0.0000".
         */
        MarketDetailDTO: {
            /** Ticker */
            ticker: string;
            /** Event Ticker */
            event_ticker?: string | null;
            /** Market Type */
            market_type?: string | null;
            /** Yes Sub Title */
            yes_sub_title?: string | null;
            /** No Sub Title */
            no_sub_title?: string | null;
            /** Title */
            title?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Status */
            status?: string | null;
            /** Open Time */
            open_time?: string | null;
            /** Close Time */
            close_time?: string | null;
            /** Yes Bid Dollars */
            yes_bid_dollars?: string | null;
            /** Yes Ask Dollars */
            yes_ask_dollars?: string | null;
            /** Last Price Dollars */
            last_price_dollars?: string | null;
            /** Volume Fp */
            volume_fp?: string | null;
            /** Volume 24H Fp */
            volume_24h_fp?: string | null;
            /** Open Interest Fp */
            open_interest_fp?: string | null;
            /** Previous Yes Bid Dollars */
            previous_yes_bid_dollars?: string | null;
            /** Previous Yes Ask Dollars */
            previous_yes_ask_dollars?: string | null;
            /** Previous Price Dollars */
            previous_price_dollars?: string | null;
            /** Notional Value Dollars */
            notional_value_dollars?: string | null;
            /** Settlement Value Dollars */
            settlement_value_dollars?: string | null;
            /** Settlement Ts */
            settlement_ts?: string | null;
            /** Strike Type */
            strike_type?: string | null;
            /** Floor Strike */
            floor_strike?: number | null;
            /** Cap Strike */
            cap_strike?: number | null;
            /** Rules Primary */
            rules_primary?: string | null;
            /** Rules Secondary */
            rules_secondary?: string | null;
            /** Is Provisional */
            is_provisional?: boolean | null;
            /** Fractional Trading Enabled */
            fractional_trading_enabled?: boolean | null;
        };
        /** MarketsPlaceholderResponse */
        MarketsPlaceholderResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Markets */
            markets: string[];
            connections: components["schemas"]["ConnectionStatus"];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Ready */
            ready: boolean;
            checks: components["schemas"]["DependencyChecks"];
        };
        /**
         * SeriesDTO
         * @description Minimal internal series representation for category navigation.
         *
         *     A series is a template for recurring events (e.g. "Monthly Jobs Report",
         *     "Daily Bitcoin Price").  The category and tags fields are the primary
         *     signals for the workstation category-level navigation pane, which lets
         *     users browse available market groups by domain (crypto, politics, sports,
         *     etc.).
         */
        SeriesDTO: {
            /** Ticker */
            ticker: string;
            /** Title */
            title?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Frequency */
            frequency?: string | null;
            /** Volume — total contracts traded across all events in this series */
            volume?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    kalshi_health_api_kalshi_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KalshiHealthResponse"];
                };
            };
        };
    };
    kalshi_get_markets_api_kalshi_markets_get: {
        parameters: {
            query?: {
                /** @description Filter by market status: unopened, open, paused, closed, settled */
                status?: string | null;
                /** @description Number of results per page (max 1000) */
                limit?: number;
                /** @description Pagination cursor from previous response */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KalshiMarketsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kalshi_get_events_api_kalshi_events_get: {
        parameters: {
            query?: {
                /** @description Filter by series ticker */
                series_ticker?: string | null;
                /** @description Filter by event status: unopened, open, closed, settled */
                status?: string | null;
                /** @description Number of results per page (max 200) */
                limit?: number;
                /** @description Pagination cursor from previous response */
                cursor?: string | null;
                /** @description When true, each event includes its nested markets */
                with_nested_markets?: boolean;
                /** @description Return only events where at least one market closes after this Unix timestamp (seconds) */
                min_close_ts?: number | null;
                /** @description Return only events with metadata updated after this Unix timestamp (seconds). Efficient for polling. */
                min_updated_ts?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KalshiEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kalshi_get_event_api_kalshi_events__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KalshiEventDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kalshi_get_series_api_kalshi_series_get: {
        parameters: {
            query?: {
                /** @description Filter by category (e.g. crypto, politics, sports) */
                category?: string | null;
                /** @description Filter by tags (comma-separated) */
                tags?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KalshiSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kalshi_get_market_api_kalshi_markets__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KalshiMarketDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_api_catalog_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
        };
    };
    get_series_api_catalog_series_get: {
        parameters: {
            query?: {
                /** @description Filter by category (case-insensitive). E.g. 'Sports', 'Crypto'. */
                category?: string | null;
                /** @description Field to sort by. */
                sort_by?: "ticker" | "title" | "category" | "frequency";
                /** @description Sort direction. */
                sort_order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_catalog_events_get: {
        parameters: {
            query?: {
                /** @description Filter by series ticker. */
                series_ticker?: string | null;
                /** @description Filter by event status: unopened | open | closed | settled. */
                status?: string | null;
                /** @description Number of results per page (max 200). */
                limit?: number;
                /** @description Pagination cursor from previous response. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_detail_api_catalog_events__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEventDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_detail_api_catalog_markets__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogMarketDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_markets_api_markets__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketsPlaceholderResponse"];
                };
            };
        };
    };
}
